#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
ENV ASPNETCORE_ENVIRONMENT=Docker
WORKDIR /app
EXPOSE 443

# Build libgdiplus with pango
RUN apt-get update && apt-get install  -y --allow-unauthenticated \
     libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
RUN apt-get update && apt-get install -y libpango1.0-dev 

RUN apt-get install -y --allow-unauthenticated git
RUN git clone https://github.com/mono/libgdiplus.git /libgdiplus
WORKDIR /libgdiplus
RUN ./autogen.sh --with-pango --prefix=/usr
RUN make  
RUN make install

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BazzucaMedia.API/bazzuca.pfx", "BazzucaMedia.API/"]
COPY ["BazzucaMedia.API/BazzucaMedia.API.csproj", "BazzucaMedia.API/"]
COPY ["BazzucaMedia.Application/BazzucaMedia.Application.csproj", "BazzucaMedia.Application/"]
COPY ["BazzucaMedia.Domain/BazzucaMedia.Domain.csproj", "BazzucaMedia.Domain/"]
COPY ["Core.Domain/Core.Domain.csproj", "Core.Domain/"]
COPY ["BazzucaMedia.DTO/BazzucaMedia.DTO.csproj", "BazzucaMedia.DTO/"]
COPY ["DB.Infra/DB.Infra.csproj", "DB.Infra/"]
COPY ["Lib/NAuth.DTO.dll", "Lib/"]
COPY ["Lib/NAuth.Client.dll", "Lib/"]
RUN dotnet restore "BazzucaMedia.API/BazzucaMedia.API.csproj"
COPY . .
WORKDIR "/src/BazzucaMedia.API"
RUN dotnet build "BazzucaMedia.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BazzucaMedia.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BazzucaMedia.API.dll"]